# Generated by Django 3.2.18 on 2023-04-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
